import type { RacerDefinition } from './types';

export const RACERS: RacerDefinition[] = [
  { id:'alchemist', name:'Alchemist', nameZh:'炼金术士', icon:'⚗', color:'#ffd629', power:'When I roll a 1 or 2 for my main move, I can move 4 instead.', powerZh:'主移动掷出 1 或 2 时，可以改为移动 4 格。' },
  { id:'blimp', name:'Blimp', nameZh:'飞艇', icon:'◒', color:'#63a9e9', power:'When I start my turn before the second corner, I get +3 to my main move. On or after it, I get -1 instead.', powerZh:'若我在第二个弯道前开始回合，本回合主移动 +3；在弯道上或之后开始则改为 -1。' },
  { id:'coach', name:'Coach', nameZh:'教练', icon:'📣', color:'#b782d0', power:'Everyone on my space gets +1 to their main move, including me.', powerZh:'与我同格的所有角色主移动 +1，包括我。' },
  { id:'baba-yaga', name:'Baba Yaga', nameZh:'芭芭雅嘎', icon:'⌂', color:'#73bce1', power:'Trip any racer that stops on my space, or when I stop on theirs.', powerZh:'任何角色停在我这格，或我停在其格时，该角色绊倒。' },
  { id:'centaur', name:'Centaur', nameZh:'半人马', icon:'♞', color:'#f28c32', power:'When I pass a racer, they move -2.', powerZh:'我超过一名角色时，该角色后退 2 格。' },
  { id:'copycat', name:'Copycat', nameZh:'模仿猫', icon:'♊', color:'#f04b2f', power:'I always have the power of a racer currently in the lead. If tied, I choose one. The copied power takes priority in a conflict.', powerZh:'我持续拥有一名当前领跑角色的能力；并列时选择其一。若能力冲突，以复制来的能力优先。' },
  { id:'banana', name:'Banana', nameZh:'香蕉', icon:'⌁', color:'#d45ab2', power:'I trip any racer that passes me.', powerZh:'任何超过我的角色都会绊倒。' },
  { id:'cheerleader', name:'Cheerleader', nameZh:'啦啦队长', icon:'✹', color:'#76bce9', power:'Before my main move, I can make the racer(s) in last place move 2. If I do, I move 1.', powerZh:'主移动前可令所有末位角色前进 2 格；若如此，我前进 1 格。' },
  { id:'dicemonger', name:'Dicemonger', nameZh:'骰子商人', icon:'⚄', color:'#f04835', power:'Any racer can reroll their main move once per turn. When another racer rerolls this way, I move 1.', powerZh:'任意角色每回合可重掷一次主移动；其他角色以此重掷时，我前进 1 格。' },
  { id:'duelist', name:'Duelist', nameZh:'决斗家', icon:'⚔', color:'#e65caa', power:'Whenever a racer shares my space, I can shout DUEL! We both roll; the higher roll moves 2. I win ties.', powerZh:'每当有角色与我同格，我可以发起“决斗”！双方掷骰，点数较高者前进 2 格；平局由我获胜。' },
  { id:'genius', name:'Genius', nameZh:'天才', icon:'⌘', color:'#ffd629', power:'I can predict my main move roll. If right, I take another turn after this one.', powerZh:'可预测主移动点数；猜中则在本回合后再行动一次。' },
  { id:'heckler', name:'Heckler', nameZh:'起哄者', icon:'!', color:'#2b9d55', power:'When a racer ends their turn within 1 space of where they started, I move 2.', powerZh:'角色回合结束时离起点位置不超过 1 格，我前进 2 格。' },
  { id:'egg', name:'Egg', nameZh:'蛋', icon:'◉', color:'#f28b2c', power:'Before my race, draw 3 racers not in this race and pick one. I have that racer\'s powers.', powerZh:'比赛前抽取 3 名未参加本局的角色并选择其一；本局中我拥有该角色的能力。' },
  { id:'gunk', name:'Gunk', nameZh:'黏液', icon:'≈', color:'#54bad1', power:'Other racers get -1 to their main move.', powerZh:'其他角色主移动 -1。' },
  { id:'huge-baby', name:'Huge Baby', nameZh:'巨婴', icon:'●', color:'#d75cb6', power:'No one can ever be on my space, except at Start. Whenever that would happen, put them one space behind me instead.', powerZh:'除起点外，任何角色都不能与我同格；若本应同格，则将其放到我后一格。' },
  { id:'flip-flop', name:'Flip Flop', nameZh:'换位怪', icon:'⇄', color:'#f14f36', power:'I can skip my main roll and swap spaces with another racer.', powerZh:'可跳过主移动掷骰，与另一名角色互换位置。' },
  { id:'hare', name:'Hare', nameZh:'野兔', icon:'➟', color:'#62bddb', power:'I get +2 to my main move. When I start my turn alone in the lead, I skip it.', powerZh:'主移动 +2；若回合开始时独自领先，则跳过主移动。' },
  { id:'hypnotist', name:'Hypnotist', nameZh:'催眠师', icon:'◉', color:'#ffe12d', power:'Before my main move, I can warp a racer to my space.', powerZh:'主移动前可将一名角色传送到我所在格。' },
  { id:'inchworm', name:'Inchworm', nameZh:'尺蠖', icon:'〰', color:'#ef4b31', power:'When another racer rolls a 1, they skip that move and I move 1.', powerZh:'其他角色主移动掷出 1 时，其跳过该移动，我前进 1 格。' },
  { id:'legs', name:'Legs', nameZh:'大长腿', icon:'Λ', color:'#82a83e', power:'I can skip rolling for my main move and move 5 instead. This counts as my main move.', powerZh:'我可以跳过主移动掷骰，改为移动 5 格；这仍算作我的主移动。' },
  { id:'mastermind', name:'Mastermind', nameZh:'幕后主脑', icon:'◇', color:'#dbe7c0', power:'At the start of my first turn, I predict the winner. If correct, the race ends immediately and I finish 2nd.', powerZh:'第一次回合开始时预测本局冠军；若预测正确，比赛立即结束且我获得第二名（也可以同时预测自己夺得第一名）。' },
  { id:'lackey', name:'Lackey', nameZh:'侍从', icon:'♟', color:'#ef4b32', power:'When another racer rolls a 6, I move 2 before they move.', powerZh:'其他角色主移动掷出 6 时，我先前进 2 格。' },
  { id:'lovable-loser', name:'Lovable Loser', nameZh:'可爱输家', icon:'◎', color:'#f28b2d', power:'Before my main move, I get 1 point if I am alone in last place.', powerZh:'主移动前若独自末位，获得 1 分。' },
  { id:'mouth', name:'M.O.U.T.H.', nameZh:'大嘴', icon:'◡', color:'#2b9e54', power:'When I stop with exactly one other racer, they are eliminated.', powerZh:'我与恰好一名其他角色同格停下时，将其淘汰。' },
  { id:'leaptoad', name:'Leaptoad', nameZh:'跳蛙', icon:'↷', color:'#f49b31', power:'While moving, I skip spaces with other racers on them.', powerZh:'移动时跳过所有有其他角色占据的格。' },
  { id:'magician', name:'Magician', nameZh:'魔术师', icon:'✦', color:'#f08d2d', power:'I can reroll my main move up to two times and must use the last roll.', powerZh:'主移动最多可重掷两次，必须使用最后一次结果。' },
  { id:'party-animal', name:'Party Animal', nameZh:'派对动物', icon:'♫', color:'#66bddb', power:'Before my main move, all other racers move 1 toward me. I get +1 to my main move for each other racer on my space.', powerZh:'主移动前，所有其他角色向我移动 1 格；每名与我同格的其他角色令我本次主移动 +1。' },
  { id:'rocket-scientist', name:'Rocket Scientist', nameZh:'火箭科学家', icon:'▲', color:'#dc59b0', power:'After rolling, I can move double and trip afterward.', powerZh:'掷骰后可移动双倍点数，移动后绊倒。' },
  { id:'sisyphus', name:'Sisyphus', nameZh:'西西弗斯', icon:'●', color:'#d6d1c1', power:'Before my race, gain 4 points. When I roll a 6 for my main move, warp to Start, lose 1 point, and do not take the main move.', powerZh:'比赛前获得 4 分；主移动掷出 6 时传回起点并失去 1 分，且不再进行本次主移动。' },
  { id:'suckerfish', name:'Suckerfish', nameZh:'吸盘鱼', icon:'➤', color:'#63afdf', power:'When a racer on my space moves, I can follow it to its new space. If I start following, I cannot stop until that move is complete.', powerZh:'与我同格的角色移动时，我可跟随到其新位置；一旦开始跟随，必须跟到该次移动全部结束。' },
  { id:'romantic', name:'Romantic', nameZh:'浪漫家', icon:'♥', color:'#a575b7', power:'When anyone stops with exactly one other racer, I move 2.', powerZh:'任何角色停在恰好两人同格的位置时，我前进 2 格。' },
  { id:'skipper', name:'Skipper', nameZh:'插队者', icon:'↺', color:'#b27ab9', power:'When anyone rolls a 1, I go next in turn order.', powerZh:'任何角色主移动掷出 1 时，我成为下一个行动者。' },
  { id:'third-wheel', name:'Third Wheel', nameZh:'第三轮', icon:'③', color:'#77a748', power:'Before my main move, I can warp to a space with exactly 2 racers.', powerZh:'主移动前可传送到恰好有 2 名角色的格。' },
  { id:'scoocher', name:'Scoocher', nameZh:'蹭步者', icon:'›', color:'#e55ba9', power:'When another racer power happens, I move 1.', powerZh:'其他角色的能力发生时，我前进 1 格。' },
  { id:'stickler', name:'Stickler', nameZh:'较真者', icon:'=', color:'#4baee1', power:'Other racers must reach the finish by exact movement or they do not move.', powerZh:'其他角色必须以恰好点数冲线；若超过终点则完全不移动。' },
  { id:'twin', name:'Twin', nameZh:'双生子', icon:'Ⅱ', color:'#62a9df', power:'Before my race, copy the power of a previous winner.', powerZh:'比赛前复制一名此前冠军的能力。' }
];

export const RACER_BY_ID = Object.fromEntries(RACERS.map(r => [r.id, r])) as Record<string, RacerDefinition>;
